version = 1
[custom]
enable_rule_generator = true
overwrite_original_rules = true

# Options for custom base configuration file
clash_rule_base = "https://raw.githubusercontent.com/weremexii/dotfile/master/subconverter/base/all_base.tpl"
surge_rule_base = "https://raw.githubusercontent.com/weremexii/dotfile/master/subconverter/base/all_base.tpl"
surfboard_rule_base = "https://raw.githubusercontent.com/weremexii/dotfile/master/subconverter/base/all_base.tpl"
mellow_rule_base = "https://raw.githubusercontent.com/weremexii/dotfile/master/subconverter/base/all_base.tpl"
quan_rule_base = "https://raw.githubusercontent.com/weremexii/dotfile/master/subconverter/base/all_base.tpl"
quanx_rule_base = "https://raw.githubusercontent.com/weremexii/dotfile/master/subconverter/base/all_base.tpl"

# Options for adding emojis
add_emoji = true
remove_old_emoji = true

# Options for filtering nodes
#include_remarks = []
#exclude_remarks = []

[[custom_groups]]
name = "ğŸš€ èŠ‚ç‚¹é€‰æ‹©"
type = "select"
rule = ["[]â™»ï¸ è‡ªåŠ¨é€‰æ‹©", "[]DIRECT", "[]ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹", "[]ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹", "[]ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹", "[]ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹", "[]ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹", "[]ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹", "[]ğŸš€ æ‰‹åŠ¨åˆ‡æ¢", "[]ğŸ’« é«˜å€ç‡èŠ‚ç‚¹", "[]ğŸ›« è´Ÿè½½å‡è¡¡"]
[[custom_groups]]
name = "â™»ï¸ è‡ªåŠ¨é€‰æ‹©"
type = "url-test"
url = "http://www.gstatic.com/generate_204"
rule = [".*"]
interval = 300
[[custom_groups]]
name = "ğŸš€ æ‰‹åŠ¨åˆ‡æ¢"
type = "select"
rule = [".*"]
[[custom_groups]]
name = "ğŸŒ å›½å†…åª’ä½“"
type = "select"
rule = ["[]DIRECT", "[]ğŸš€ èŠ‚ç‚¹é€‰æ‹©", "[]â™»ï¸ è‡ªåŠ¨é€‰æ‹©", "[]ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹", "[]ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹", "[]ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹", "[]ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹", "[]ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹", "[]ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹", "[]ğŸš€ æ‰‹åŠ¨åˆ‡æ¢", "[]ğŸ’« é«˜å€ç‡èŠ‚ç‚¹", "[]ğŸ›« è´Ÿè½½å‡è¡¡"]
[[custom_groups]]
name = "ğŸŒ å›½å¤–åª’ä½“"
type = "select"
rule = ["[]ğŸš€ èŠ‚ç‚¹é€‰æ‹©", "[]â™»ï¸ è‡ªåŠ¨é€‰æ‹©", "[]DIRECT", "[]ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹", "[]ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹", "[]ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹", "[]ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹", "[]ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹", "[]ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹", "[]ğŸš€ æ‰‹åŠ¨åˆ‡æ¢", "[]ğŸ’« é«˜å€ç‡èŠ‚ç‚¹", "[]ğŸ›« è´Ÿè½½å‡è¡¡"]
[[custom_groups]]
name = "ğŸ“š å­¦æœ¯å¹³å°"
type = "select"
rule = ["[]ğŸš€ èŠ‚ç‚¹é€‰æ‹©", "[]â™»ï¸ è‡ªåŠ¨é€‰æ‹©", "[]DIRECT", "[]ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹", "[]ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹", "[]ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹", "[]ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹", "[]ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹", "[]ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹", "[]ğŸš€ æ‰‹åŠ¨åˆ‡æ¢", "[]ğŸ’« é«˜å€ç‡èŠ‚ç‚¹", "[]ğŸ›« è´Ÿè½½å‡è¡¡"]
[[custom_groups]]
name = "ğŸ“² ç”µæŠ¥æ¶ˆæ¯"
type = "select"
rule = ["[]ğŸš€ èŠ‚ç‚¹é€‰æ‹©", "[]â™»ï¸ è‡ªåŠ¨é€‰æ‹©", "[]DIRECT", "[]ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹", "[]ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹", "[]ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹", "[]ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹", "[]ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹", "[]ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹", "[]ğŸš€ æ‰‹åŠ¨åˆ‡æ¢", "[]ğŸ’« é«˜å€ç‡èŠ‚ç‚¹", "[]ğŸ›« è´Ÿè½½å‡è¡¡"]
[[custom_groups]]
name = "ğŸ“¹ æ²¹ç®¡è§†é¢‘"
type = "select"
rule = ["[]ğŸš€ èŠ‚ç‚¹é€‰æ‹©", "[]â™»ï¸ è‡ªåŠ¨é€‰æ‹©", "[]DIRECT", "[]ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹", "[]ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹", "[]ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹", "[]ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹", "[]ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹", "[]ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹", "[]ğŸš€ æ‰‹åŠ¨åˆ‡æ¢", "[]ğŸ’« é«˜å€ç‡èŠ‚ç‚¹", "[]ğŸ›« è´Ÿè½½å‡è¡¡"]
[[custom_groups]]
name = "ğŸ® æ¸¸æˆä»£ç†"
type = "select"
rule = ["[]ğŸš€ èŠ‚ç‚¹é€‰æ‹©", "[]â™»ï¸ è‡ªåŠ¨é€‰æ‹©", "[]DIRECT", "[]ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹", "[]ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹", "[]ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹", "[]ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹", "[]ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹", "[]ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹", "[]ğŸš€ æ‰‹åŠ¨åˆ‡æ¢", "[]ğŸ’« é«˜å€ç‡èŠ‚ç‚¹", "[]ğŸ›« è´Ÿè½½å‡è¡¡"]
[[custom_groups]]
name = "ğŸ§‘â€ğŸ’» GitHub"
type = "select"
rule = ["[]ğŸš€ èŠ‚ç‚¹é€‰æ‹©", "[]â™»ï¸ è‡ªåŠ¨é€‰æ‹©", "[]DIRECT", "[]ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹", "[]ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹", "[]ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹", "[]ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹", "[]ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹", "[]ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹", "[]ğŸš€ æ‰‹åŠ¨åˆ‡æ¢", "[]ğŸ’« é«˜å€ç‡èŠ‚ç‚¹", "[]ğŸ›« è´Ÿè½½å‡è¡¡"]
[[custom_groups]]
name = "ğŸ“º å·´å“ˆå§†ç‰¹"
type = "select"
rule = ["[]ğŸš€ èŠ‚ç‚¹é€‰æ‹©", "[]â™»ï¸ è‡ªåŠ¨é€‰æ‹©", "[]ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹", "[]ğŸš€ æ‰‹åŠ¨åˆ‡æ¢"]
[[custom_groups]]
name = "ğŸ“º å“”å“©å“”å“©"
type = "select"
rule = ["[]DIRECT", "[]ğŸš€ èŠ‚ç‚¹é€‰æ‹©", "[]â™»ï¸ è‡ªåŠ¨é€‰æ‹©", "[]ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹", "[]ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹", "[]ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹", "[]ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹", "[]ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹", "[]ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹", "[]ğŸš€ æ‰‹åŠ¨åˆ‡æ¢", "[]ğŸ’« é«˜å€ç‡èŠ‚ç‚¹", "[]ğŸ›« è´Ÿè½½å‡è¡¡"]
[[custom_groups]]
name = "ğŸ“¢ è°·æ­ŒFCM"
type = "select"
rule = ["[]ğŸš€ èŠ‚ç‚¹é€‰æ‹©", "[]â™»ï¸ è‡ªåŠ¨é€‰æ‹©", "[]DIRECT", "[]ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹", "[]ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹", "[]ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹", "[]ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹", "[]ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹", "[]ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹", "[]ğŸš€ æ‰‹åŠ¨åˆ‡æ¢", "[]ğŸ’« é«˜å€ç‡èŠ‚ç‚¹", "[]ğŸ›« è´Ÿè½½å‡è¡¡"]
[[custom_groups]]
name = "â“‚ï¸ å¾®è½¯äº‘ç›˜"
type = "select"
rule = ["[]DIRECT", "[]ğŸš€ èŠ‚ç‚¹é€‰æ‹©", "[]â™»ï¸ è‡ªåŠ¨é€‰æ‹©", "[]ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹", "[]ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹", "[]ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹", "[]ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹", "[]ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹", "[]ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹", "[]ğŸ’« é«˜å€ç‡èŠ‚ç‚¹", "[]ğŸ›« è´Ÿè½½å‡è¡¡", "[]ğŸš€ æ‰‹åŠ¨åˆ‡æ¢"]
[[custom_groups]]
name = "â“‚ï¸ å¾®è½¯æœåŠ¡"
type = "select"
rule = ["[]DIRECT", "[]ğŸš€ èŠ‚ç‚¹é€‰æ‹©", "[]â™»ï¸ è‡ªåŠ¨é€‰æ‹©", "[]ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹", "[]ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹", "[]ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹", "[]ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹", "[]ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹", "[]ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹", "[]ğŸ’« é«˜å€ç‡èŠ‚ç‚¹", "[]ğŸ›« è´Ÿè½½å‡è¡¡", "[]ğŸš€ æ‰‹åŠ¨åˆ‡æ¢"]
[[custom_groups]]
name = "ğŸ è‹¹æœæœåŠ¡"
type = "select"
rule = ["[]DIRECT", "[]ğŸš€ èŠ‚ç‚¹é€‰æ‹©", "[]â™»ï¸ è‡ªåŠ¨é€‰æ‹©", "[]ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹", "[]ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹", "[]ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹", "[]ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹", "[]ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹", "[]ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹", "[]ğŸ’« é«˜å€ç‡èŠ‚ç‚¹", "[]ğŸ›« è´Ÿè½½å‡è¡¡", "[]ğŸš€ æ‰‹åŠ¨åˆ‡æ¢"]
[[custom_groups]]
name = "ğŸ® æ¸¸æˆå¹³å°"
type = "select"
rule = ["[]DIRECT", "[]ğŸš€ èŠ‚ç‚¹é€‰æ‹©", "[]â™»ï¸ è‡ªåŠ¨é€‰æ‹©", "[]ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹", "[]ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹", "[]ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹", "[]ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹", "[]ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹", "[]ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹", "[]ğŸ’« é«˜å€ç‡èŠ‚ç‚¹", "[]ğŸ›« è´Ÿè½½å‡è¡¡", "[]ğŸš€ æ‰‹åŠ¨åˆ‡æ¢"]
[[custom_groups]]
name = "ğŸ¨ æ¼«ç”»å¹³å°"
type = "select"
rule = ["[]DIRECT", "[]ğŸš€ èŠ‚ç‚¹é€‰æ‹©", "[]â™»ï¸ è‡ªåŠ¨é€‰æ‹©", "[]ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹", "[]ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹", "[]ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹", "[]ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹", "[]ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹", "[]ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹", "[]ğŸ’« é«˜å€ç‡èŠ‚ç‚¹", "[]ğŸ›« è´Ÿè½½å‡è¡¡", "[]ğŸš€ æ‰‹åŠ¨åˆ‡æ¢"]
[[custom_groups]]
name = "ğŸ¯ å…¨çƒç›´è¿"
type = "select"
rule = ["[]DIRECT", "[]ğŸš€ èŠ‚ç‚¹é€‰æ‹©"]
[[custom_groups]]
name = "ğŸ›‘ å¹¿å‘Šæ‹¦æˆª"
type = "select"
rule = ["[]REJECT", "[]DIRECT", "[]ğŸš€ èŠ‚ç‚¹é€‰æ‹©"]
[[custom_groups]]
name = "ğŸŸ æ¼ç½‘ä¹‹é±¼"
type = "select"
rule = ["[]ğŸš€ èŠ‚ç‚¹é€‰æ‹©", "[]â™»ï¸ è‡ªåŠ¨é€‰æ‹©", "[]DIRECT", "[]ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹", "[]ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹", "[]ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹", "[]ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹", "[]ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹", "[]ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹", "[]ğŸš€ æ‰‹åŠ¨åˆ‡æ¢", "[]ğŸ’« é«˜å€ç‡èŠ‚ç‚¹", "[]ğŸ›« è´Ÿè½½å‡è¡¡"]
[[custom_groups]]
name = "ğŸ›« è´Ÿè½½å‡è¡¡"
type = "load-balance"
rule = ["(æ¸¯|HK|Hong Kong)(?!.*(IPLC|iplc|ä¸“çº¿|æ¸¸æˆ|Game|GAME))"]
url = "http://www.gstatic.com/generate_204"
interval = 300
strategy = "round-robin"
[[custom_groups]]
name = "ğŸ’« é«˜å€ç‡èŠ‚ç‚¹"
type = "select"
rule = ["(IPLC|iplc|ä¸“çº¿|æ¸¸æˆ|Game|GAME)"]
[[custom_groups]]
name = "ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹"
type = "url-test"
rule = ["(æ¸¯|HK|Hong Kong)(?!.*(IPLC|iplc|ä¸“çº¿|æ¸¸æˆ|Game|GAME))"]
url = "http://www.gstatic.com/generate_204"
interval = 300
[[custom_groups]]
name = "ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹"
type = "url-test"
rule = ["(æ—¥æœ¬|å·æ—¥|ä¸œäº¬|å¤§é˜ª|æ³‰æ—¥|åŸ¼ç‰|æ²ªæ—¥|æ·±æ—¥|[^-]æ—¥|JP|Japan)(?!.*(IPLC|iplc|ä¸“çº¿|æ¸¸æˆ|Game|GAME))"]
url = "http://www.gstatic.com/generate_204"
interval = 300
[[custom_groups]]
name = "ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹"
type = "url-test"
rule = ["(ç¾|æ³¢ç‰¹å…°|è¾¾æ‹‰æ–¯|ä¿„å‹’å†ˆ|å‡¤å‡°åŸ|è´¹åˆ©è’™|ç¡…è°·|æ‹‰æ–¯ç»´åŠ æ–¯|æ´›æ‰çŸ¶|åœ£ä½•å¡|åœ£å…‹æ‹‰æ‹‰|è¥¿é›…å›¾|èŠåŠ å“¥|US|United States)(?!.*(IPLC|iplc|ä¸“çº¿|æ¸¸æˆ|Game|GAME))"]
url = "http://www.gstatic.com/generate_204"
interval = 300
[[custom_groups]]
name = "ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹"
type = "url-test"
rule = ["(å°|æ–°åŒ—|å½°åŒ–|TW|Taiwan)(?!.*(IPLC|iplc|ä¸“çº¿|æ¸¸æˆ|Game|GAME))"]
url = "http://www.gstatic.com/generate_204"
interval = 300
[[custom_groups]]
name = "ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹"
type = "url-test"
rule = ["(æ–°åŠ å¡|å¡|ç‹®åŸ|SG|Singapore)(?!.*(IPLC|iplc|ä¸“çº¿|æ¸¸æˆ|Game|GAME))"]
url = "http://www.gstatic.com/generate_204"
interval = 300
[[custom_groups]]
name = "ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹"
type = "url-test"
rule = ["(KR|Korea|KOR|é¦–å°”|éŸ©|éŸ“)(?!.*(IPLC|iplc|ä¸“çº¿|æ¸¸æˆ|Game|GAME))"]
url = "http://www.gstatic.com/generate_204"
interval = 300

#[[rulesets]]
#import = ""
[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list"
interval = 86400
[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list"
interval = 86400
[[rulesets]]
group = "ğŸ›‘ å¹¿å‘Šæ‹¦æˆª"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list"
interval = 86400
[[rulesets]]
group = "ğŸ“¢ è°·æ­ŒFCM"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleFCM.list"
interval = 86400
[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GoogleCN.list"
interval = 86400
[[rulesets]]
group = "â“‚ï¸ å¾®è½¯äº‘ç›˜"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/OneDrive.list"
interval = 86400
[[rulesets]]
group = "â“‚ï¸ å¾®è½¯æœåŠ¡"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Microsoft.list"
interval = 86400
[[rulesets]]
group = "ğŸ è‹¹æœæœåŠ¡"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Apple.list"
interval = 86400
[[rulesets]]
group = "ğŸ“š å­¦æœ¯å¹³å°"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/OpenAi.list"
interval = 86400
[[rulesets]]
group = "ğŸ“š å­¦æœ¯å¹³å°"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Scholar.list"
interval = 86400
[[rulesets]]
group = "ğŸ“² ç”µæŠ¥æ¶ˆæ¯"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Telegram.list"
interval = 86400
[[rulesets]]
group = "ğŸ® æ¸¸æˆä»£ç†"
ruleset = "https://raw.githubusercontent.com/weremexii/dotfile/master/subconverter/ruleset/game_proxy.list"
interval = 86400
[[rulesets]]
group = "ğŸ§‘â€ğŸ’» GitHub"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Github.list"
interval = 86400
[[rulesets]]
group = "ğŸ® æ¸¸æˆå¹³å°"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Epic.list"
interval = 86400
[[rulesets]]
group = "ğŸ® æ¸¸æˆå¹³å°"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Sony.list"
interval = 86400
[[rulesets]]
group = "ğŸ® æ¸¸æˆå¹³å°"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Steam.list"
interval = 86400
[[rulesets]]
group = "ğŸ¨ æ¼«ç”»å¹³å°"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/EHGallery.list"
interval = 86400
[[rulesets]]
group = "ğŸ¨ æ¼«ç”»å¹³å°"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Pixiv.list"
interval = 86400
[[rulesets]]
group = "ğŸ“¹ æ²¹ç®¡è§†é¢‘"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/YouTube.list"
interval = 86400
[[rulesets]]
group = "ğŸ“º å·´å“ˆå§†ç‰¹"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Bahamut.list"
interval = 86400
[[rulesets]]
group = "ğŸ“º å“”å“©å“”å“©"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/BilibiliHMT.list"
interval = 86400
[[rulesets]]
group = "ğŸ“º å“”å“©å“”å“©"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Bilibili.list"
interval = 86400
[[rulesets]]
group = "ğŸŒ å›½å†…åª’ä½“"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaMedia.list"
interval = 86400
[[rulesets]]
group = "ğŸŒ å›½å¤–åª’ä½“"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyMedia.list"
interval = 86400
[[rulesets]]
group = "ğŸš€ èŠ‚ç‚¹é€‰æ‹©"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyGFWlist.list"
interval = 86400
[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list"
interval = 86400
[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list"
interval = 86400
[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Download.list"
interval = 86400
[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "https://raw.githubusercontent.com/weremexii/dotfile/master/subconverter/ruleset/addition_direct.list"
interval = 86400
[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "[]GEOIP,CN"
[[rulesets]]
group = "ğŸŸ æ¼ç½‘ä¹‹é±¼"
ruleset = "[]FINAL"

[[template_args]]
key = "clash.allow_lan"
value = "false"